### PR TITLE
option for not saving checkbox state regardless of globally save state setting of datatable.

### PR DESCRIPTION
**Pull request by susgo**
comments #57 

Probable not ready.

````
var table = $('#example').DataTable({
    'ajax': 'http://api.myjson.com/bins/sh72r',
    'columns': [
      {
        'className':      'details-control',
        'orderable':      false,
        'data':           null,
        'defaultContent': ''
      },
      {
        'data': 'DT_RowId',
        'checkboxes': {
          'selectRow': true,
          'stateSave': false
        }
      },
      { 'data': 'first_name' },
      { 'data': 'last_name' },
      { 'data': 'position' },
      { 'data': 'office' },
      { 'data': 'salary' }
    ],
    'ignoreSelect': true,
    'select': {
      'style': 'multi',
      'selector': 'td:not(:first-child)'
    },
    'stateSave': true,
    'order': [[3, 'asc']]
  } );
````

### CODE REVIEW

**Comment by susgo** [comment]
@mpryvkin Solves #57. In addition `createdCell` can be used to render selection state from the database values.

**Comment by mpryvkin** [comment]
Thanks for contributing. 

I used your idea in the latest commit https://github.com/gyrocode/jquery-datatables-checkboxes/commit/9796ea9afa0b917d045559a9bee8b77d36bd26ff.

However changes needed in other areas of the code because state saving occurs in more than one place.

Also I would prefer to use option with the same name as DataTables [`stateSave`](https://datatables.net/reference/option/stateSave) rather than `saveState`.

**Comment by susgo** [comment]
Okay, thanks! And sorry for the naming. Hopefully I can contribute with other issues again. 😊

**Comment by mpryvkin** [comment]
I appreciate your suggestions :)

**Pull request closed without merging**
