### PR TITLE
Ability to style checkbox, define its width and highlight rows by cli…

### PR DESCRIPTION
**Pull request by s0By**
Please review my pull request.

I added the ability to define checkbox element, which I think is really needed in this solution.
It has different checks so it's probably hard to break the solution.
Since custom checkbox definition is a more advanced feature, you need to define width as well, otherwise your view will be probably messed up, because usually 1% is not enough.

The other use case which was pretty crucial in my case (for example), I needed to see selected rows (selected class) just by click on checkboxes without extra unneeded extensions like Select, pretty easy and straightforward.

And last but not least, I think it's pretty confusing and unnecessary to have the ability to select all by click on heading, so I'd propose to remove this ability. There is always a human factor when you accidentally click on empty space and the selection gets annoying. Also concept of clicking on checkboxes in current case kinda differs, in table users can only click on checkbox and in heading they have a little extra...

I made the changes only to not minified file, everyone has different minification tools.
Namings of variables etc may not be the best, so you can change that.

P.S. 
Custom checkboxes are usually wrapped inside `<div>` or `<label>`, something like:
```
<div class="checkbox">
    <input id="checkbox1" class="styled" type="checkbox">
    <label for="checkbox1"></label>
</div>
```
```
<label>
   <input type="checkbox">
   <span></span>
</label>
```

"Div" method is slowly dying, it has more appearance issues in browsers and you need to always have an id for an input, since input itself is hidden.

### CODE REVIEW

**Comment by mpryvkin** [comment]
Thank you for your contribution, I appreciate your time.

You make a good point about the need to be able to specify width and custom HTML content for checkbox element. However I'm planning to allow the use of existing `columns.width` and `columns.render` options rather than defining new ones with the same meaning. I will address this issue in one of the next updates.

In version 1.2.0 I made the decision to rely on Select extension for row selection which needs to be included if row selection is required. Although I may reconsider this decision later.

I disagree with you on removing "select all" functionality, this part is a core feature of this plug-in. Also "select all" control can be disabled by `checkboxes.selectAll` option if you don't want to use it.

I am closing this pull request for now and will address the issues with width and custom content in one of the next updates. 

Thanks again!

**Comment by mpryvkin** [comment]
Just pushed an update adding the ability to use `columns.width`, `columns.className` and `columns.render` options to override default behavior.

Default implementation of the `columns.render` function returns the following string `<input type="checkbox" class="dt-checkboxes">`. If you customize content of the cell containing checkboxes, this element **must be** present for proper functioning.

**Comment by s0By** [comment]
The problem with `Select` extension is that It will select the row as soon as user clicks whereever he wants in the row (which is bad). 
Yes, maybe in some use cases it will be good, generally when working with simple text data. But if datatable is more "advanced" you have different actions in it etc and those extra clicks/missclicks will select the row which is confusing. 

My idea was to have a simple row selection only by pressing the checkbox. 
Same goes for selectAll, the functionality itself is needed and is very crucial, but clicking on empty space is not, if you don't want to remove it, maybe you could consider making `th` clicks as an option.

**Comment by mpryvkin** [comment]
You can limit elements that trigger row selection by using [`select.selector`](https://datatables.net/reference/option/select.selector) option. For example, `selector: 'td:first-child'` to select only by using first column.

I will think about disabling selection on the cell itself.

**Comment by s0By** [comment]
Yes, sorry for the false statement. This does the trick indeed:
```
select: {
        info: false,
        selector: 'td:first-child input[type="checkbox"]'
}
```
I don't remember what was my exact reason for creating my solution, but I think I just didn't want to have extra dependency for such a simple task as `.addClass("selected")`

**Pull request closed without merging**
